# Generated by Django 3.2.7 on 2021-09-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_department_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoPrint',
        ),
    ]
